export const LOGICAL_WIDTH = 480;
export const LOGICAL_HEIGHT = 720;
export const FIXED_DT = 1 / 60;
export const GRAVITY = -25;          // world units/s²
export const FLAP_VELOCITY = 9;      // world units/s upward
export const SCROLL_SPEED = 120;     // world units/s (pipes move left)
export const PIPE_GAP = 150;         // world units between top/bottom pipe
export const PIPE_WIDTH = 52;        // world units
export const GROUND_HEIGHT = 80;     // world units from bottom of logical area
export const BIRD_WIDTH = 34;
export const BIRD_HEIGHT = 24;
